name: Setup Python and Poetry environment

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Load cached Poetry installation
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: local-${{ runner.os }}-${{ hashFiles('.github/actions/python-setup/action.yml') }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Load cached virtual environment
      id: cached-venv
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install project dependencies
      if: steps.cached-venv.outputs.cache-hit != 'true'
      shell: bash
      run: |
        poetry install --no-interaction --no-root
    - name: Set version string based on tag
      shell: bash
      run: |
        export VERSION_NUMBER="$(git describe --tags --abbrev=8 | sed 's/-.*g/+/' | tr -d 'v')"
        sed -i "s/version = \"0.0.0\"/version = \"${VERSION_NUMBER}\"/" pyproject.toml
        sed -i "s/__version__ = '0.0.0'/__version__ = '${VERSION_NUMBER}'/" chrome_local_storage/__init__.py
